language: php
php:
  - 7.0
matrix:
  fast_finish: true
addons:
  hosts:
    - localhost
cache:
  directories:
    - ${HOME}/.composer/cache
    # This is where vendor/ backups will be stored.
    - ${HOME}/vendor-cache/
git:
  depth: 3
before_install: ${TRAVIS_BUILD_DIR}/build/travis/before_install.sh
install: ${TRAVIS_BUILD_DIR}/build/travis/install.sh
script: ${TRAVIS_BUILD_DIR}/build/travis/script.sh
before_cache: ${TRAVIS_BUILD_DIR}/build/travis/before_cache.sh
